CREATE OR REPLACE VIEW DWH_EXPORT_SALES AS
SELECT 
    CAE.ID AS ID_OPERACION,
    CAE.ID_CLIENTE,
    CAE.ID_EMPRESA,
    CAE.ID_SUCURSAL,
    CAE.ID_EMPRESA || '-' || CAE.ID_SUCURSAL AS KEY_EMP_SUC,
    CAE.ID_EMPRESA || '-' || CAE.ID_CLIENTE AS KEY_EMP_CLI,
    MAE.ID_AGENTE,
    'EXPORTACION' AS DEPARTAMENTO,
    'AEREO' AS VIA,
    CAE.FECHA_CARGA,
    TXC.DESCRIPCION AS TRAFICO_DESCRIPCION,
    NVL(TXC.CODIGO, COUNTRY_LOAD.DESCRIPCION) AS TRAFICO,
    CAE.TIPO_OPERACION,
    CLIENT.RAZON_SOCIAL AS CLIENTE_RAZON_SOCIAL,
    CLIENT.DESCRIP_CORTA AS CLIENTE_DESC_CORTA,
    CASE 
        WHEN CAE.TIPO_TRANSBORDO = 'TRANSBORDO_PROPIO' THEN 'S'
        WHEN AIRPORT_DISCHARGE.ID_PAIS != CITY_DESTINATION.ID_PAIS THEN 'S'
        WHEN CLIENT.ID = (
            SELECT PE.VALOR_NUMERICO 
            FROM COMPANY_PARAMETERS PE 
            WHERE PE.ID_PARAMETRO_EMP_BASE = 30 
              AND PE.ID_EMPRESA = CAE.ID_EMPRESA
        ) THEN 'S'
        ELSE 'N' 
    END AS ES_TRANSBORDO,
    AGENT.DESCRIP_CORTA AS AGENTE_DESC,
    AGENT.RAZON_SOCIAL AS AGENTE_RAZON_SOCIAL,
    AIRPORT_LOAD.DESCRIPCION AS AEROPUERTO_CARGA,
    AIRPORT_DISCHARGE.DESCRIPCION AS AEROPUERTO_DESCARGA,
    CITY_ORIGIN.DESCRIPCION AS CIUDAD_TOMA,
    CITY_DESTINATION.DESCRIPCION AS CIUDAD_DESTINO,
    COUNTRY_LOAD.DESCRIPCION AS PAIS_CARGA,
    COUNTRY_DISCHARGE.DESCRIPCION AS PAIS_DESCARGA,
    CAE.FLETE_CERRADO_POR,
    CAE.PESO,
    CAE.VOLUMEN,
    ROUND(CAE.UM, 2) AS UNIDAD_MEDIDA,
    CONT.CONTENEDORES_DESCRIPCION,
    AIRLINE.DESCRIP_CORTA AS AEROLINEA,
    BRANCH.DESCRIPCION AS SUCURSAL_DESC,
    CAE.SEGURO,
    SELLER.DESCRIPCION AS VENDEDOR_DESC,
    CITY_SALE.DESCRIP_CORTA AS CIUDAD_VENTA,
    CLIENT.ES_GLOBAL_ACCOUNT

FROM CHILD_AIR_EXPORT CAE
INNER JOIN MASTER_AIR_EXPORT MAE 
    ON CAE.ID_MEA = MAE.ID
LEFT JOIN AIRPORTS AIRPORT_LOAD 
    ON MAE.ID_AEROPUERTO_DEPARTURE = AIRPORT_LOAD.ID
LEFT JOIN AIRPORTS AIRPORT_DISCHARGE 
    ON MAE.ID_AEROPUERTO_PRIMERA = AIRPORT_DISCHARGE.ID
LEFT JOIN CITIES CITY_DESTINATION 
    ON CAE.ID_CIUDAD_DESTINO = CITY_DESTINATION.ID
LEFT JOIN CITIES CITY_ORIGIN 
    ON CAE.ID_CIUDAD_VENTA = CITY_ORIGIN.ID
LEFT JOIN ENTITIES AGENT 
    ON MAE.ID_AGENTE = AGENT.ID
LEFT JOIN ENTITIES CLIENT 
    ON CAE.ID_CLIENTE = CLIENT.ID
LEFT JOIN COUNTRIES COUNTRY_LOAD 
    ON AIRPORT_LOAD.ID_PAIS = COUNTRY_LOAD.ID
LEFT JOIN COUNTRIES COUNTRY_DISCHARGE 
    ON AIRPORT_DISCHARGE.ID_PAIS = COUNTRY_DISCHARGE.ID
LEFT JOIN CITIES CITY_SALE 
    ON CAE.ID_CIUDAD_VENTA = CITY_SALE.ID
LEFT JOIN APP_USERS SELLER 
    ON CAE.ID_VENDEDOR = SELLER.ID
LEFT JOIN ENTITIES AIRLINE 
    ON MAE.ID_AEROLINEA_PRIMERA = AIRLINE.ID
LEFT JOIN BRANCHES BRANCH 
    ON CAE.ID_SUCURSAL = BRANCH.ID
LEFT JOIN (
    SELECT CE.ID_CIUDAD, MAX(T.DESCRIPCION) AS DESCRIPCION, MAX(T.DESCRIP_CORTA) AS CODIGO
    FROM TRAFFICS T
    INNER JOIN COMPANY_CITIES CE 
        ON CE.ID_EMPRESA = T.ID_EMPRESA 
       AND CE.ID_TRAFICO = T.ID
    GROUP BY CE.ID_CIUDAD
) TXC 
    ON AIRPORT_DISCHARGE.ID_CIUDAD = TXC.ID_CIUDAD
LEFT JOIN (
    SELECT CON.ID_HIJO, LISTAGG(TC.DESCRIP_CORTA, ', ') WITHIN GROUP (ORDER BY TC.ID) AS CONTENEDORES_DESCRIPCION
    FROM CONTAINERS_BY_CHILD CON
    INNER JOIN CONTAINER_TYPES TC 
        ON CON.ID_TIPO_CONTENEDOR = TC.ID
    WHERE CON.VIA = 'MARITIMO' 
      AND CON.DEPARTAMENTO = 'EXPORTACION' 
      AND CON.TIPO_OPERACION = 'FCL'
    GROUP BY CON.ID_HIJO
) CONT 
    ON CAE.ID = CONT.ID_HIJO

WHERE CAE.DT_ALTA > TO_DATE('2018-01-01', 'YYYY-MM-DD');